export const CTranslateWorld = {
  CREATE_ACCOUNTING_ENTER: "ثبت ورود حسابداری",
  CREATE_ACCOUNTING_EXIT: "ثبت خروج حسابداری",
  CREATE_BLOG: "ایجاد بلاگ",
  CREATE_ECONOMIC_PACKAGE: "ایجاد بسته اقتصادی",
  CREATE_FACTOR: "ایجاد فاکتور",
  CREATE_IMAGE: "ایجاد تصویر",
  CREATE_MENU_CATEGORY: "ایجاد دسته منو",
  CREATE_MENU_PRODUCT: "ایجاد محصول منو",
  CREATE_ORDER: "ایجاد سفارش",
  CREATE_ORDER_LOCATION: "ایجاد موقعیت سفارش",
  CREATE_ROLE: "ایجاد نقش",
  CREATE_USER: "ایجاد کاربر",
  CREATE_WAREHOUSE_ENTER: "ثبت ورود انبار",
  CREATE_WAREHOUSE_EXIT: "ثبت خروج انبار",
  DELETE_ACCOUNTING_EXIT: "حذف خروج حسابداری",
  DELETE_BLOG: "حذف بلاگ",
  DELETE_FACTOR: "حذف فاکتور",
  DELETE_IMAGE: "حذف تصویر",
  DELETE_MENU_CATEGORY: "حذف دسته منو",
  DELETE_MENU_PRODUCT: "حذف محصول منو",
  DELETE_ORDER: "حذف سفارش",
  DELETE_ORDER_LOCATION: "حذف موقعیت سفارش",
  DELETE_ROLE: "حذف نقش",
  DELETE_USER: "حذف کاربر",
  DELETE_WAREHOUSE_ENTER: "حذف ورود انبار",
  DELETE_WAREHOUSE_EXIT: "حذف خروج انبار",
  EDIT_PASSWORD: "ویرایش رمز عبور",
  EDIT_PROFILE: "ویرایش پروفایل",
  READ_ACCOUNTING_ENTER: "مشاهده ورود حسابداری",
  READ_ACCOUNTING_EXIT: "مشاهده خروج حسابداری",
  READ_ALL_ONLINE_SHOP: "مشاهده تمام فروشگاه آنلاین",
  READ_BLOG: "مشاهده بلاگ",
  READ_ECONOMIC_PACKAGE: "مشاهده بسته اقتصادی",
  READ_FACTOR: "مشاهده فاکتور",
  READ_IMAGE: "مشاهده تصویر",
  READ_MENU_CATEGORY: "مشاهده دسته منو",
  READ_MENU_PRODUCT: "مشاهده محصول منو",
  READ_ORDER: "مشاهده سفارش",
  READ_ORDER_LOCATION: "مشاهده موقعیت سفارش",
  READ_ROLE: "مشاهده نقش",
  READ_SNAP_ONLINE_SHOP: "مشاهده فروشگاه آنلاین اسنپ",
  READ_TAPSI_ONLINE_SHOP: "مشاهده فروشگاه آنلاین تپسی",
  READ_USER: "مشاهده کاربر",
  READ_WAREHOUSE_ENTER: "مشاهده ورود انبار",
  READ_WAREHOUSE_EXIT: "مشاهده خروج انبار",
  UPDATE_ACCOUNTING_EXIT: "بروزرسانی خروج حسابداری",
  UPDATE_BLOG: "بروزرسانی بلاگ",
  UPDATE_FACTOR: "بروزرسانی فاکتور",
  UPDATE_MENU_CATEGORY: "بروزرسانی دسته منو",
  UPDATE_MENU_PRODUCT: "بروزرسانی محصول منو",
  UPDATE_ORDER: "بروزرسانی سفارش",
  UPDATE_ORDER_LOCATION: "بروزرسانی موقعیت سفارش",
  UPDATE_ROLE: "بروزرسانی نقش",
  UPDATE_USER: "بروزرسانی کاربر",
  UPDATE_WAREHOUSE_ENTER: "بروزرسانی ورود انبار",
  UPDATE_WAREHOUSE_EXIT: "بروزرسانی خروج انبار",
};
