export enum EInnerRoute {
  // PROTOCOL = "http",
  PROTOCOL = "https",
  // DOMAIN = "127.0.0.1:3000",
  // DOMAIN = "192.168.1.109:8080",
  DOMAIN = "shonan.ir",
  HOST = `${PROTOCOL}://${DOMAIN}`,
  // app
  HOME                 = "/",
  ABOUT_US             = "/about-us",
  ACCOUNT              = "/account",
  ACCOUNT_FACTOR       = "/account/factor",
  BLOG                 = "/blog",
  CONTACT_US           = "/contact-us",
  FAQ                  = "/faq",
  MENU                 = "/menu",
  MENU_CATEGORY        = "/menu/category",
  MENU_PRODUCT         = "/menu/product",
  NEWS                 = "/news",
  ORDER                = "/order",
  ORDER_PRESENT        = "/order/present",
  ORDER_PRESENT_ORDER  = "/order/present/order",
  ORDER_TRANSFER       = "/order/transfer",
  PACKAGE              = "/package",
  PRODUCT              = "/product",
  QUESTION             = "/question",
  SEARCH               = "/search",
  SERVICE              = "/service",
}
