export enum ERoute {
  // PROTOCOL = "http",
  PROTOCOL = "https",
  // DOMAIN = "127.0.0.1:8080",
  DOMAIN = "api.choconan.ir",
  HOST = `${PROTOCOL}://${DOMAIN}`,
  // HOST = "http://127.0.0.1:8080",
  // HOST = "http://192.168.1.100:8080",
  // HOST = "https://api.choconan.ir",
  // app
  GET_VIDEO      = "/video",
  GET_LAST_VIDEO = "/last-video",
  // menu
  GET_FULL_MENU                   = "/menu",
  SEARCH_ON_MENU                  = "/search",
  ADD_CATEGORY_MENU               = "/category-menu",
  UPDATE_CATEGORY_MENU            = "/category-menu",
  DELETE_CATEGORY_MENU            = "/category-menu",
  ADD_PRODUCT_MENU                = "/product-menu",
  UPDATE_PRODUCT_MENU             = "/product-menu",
  DELETE_PRODUCT_MENU             = "/product-menu",
  GET_ECONOMIC_PACKAGES           = "/economic-package",
  ADD_ECONOMIC_PACKAGE            = "/economic-package",
  UPDATE_ECONOMIC_PACKAGE         = "/economic-package",
  DELETE_ECONOMIC_PACKAGE         = "/economic-package",
  ADD_CONTENT_ECONOMIC_PACKAGE    = "/content-economic-package",
  DELETE_CONTENT_ECONOMIC_PACKAGE = "/content-economic-package",
  //service
  GET_CRAWLER_MENU_SNAP_FOOD      = "/menu-snap",
  GET_CRAWLER_MENU_TAPSI_FOOD     = "/menu-tapsi",
  // order
  GET_TABLES            = "/table",
  CREATE_TABLE          = "/table",
  DELETE_TABLE          = "/table",
  GET_STATUS_TABLE      = "/status-table",
  EDITABLE_STATUS_TABLE = "/status-table",
  DELETE_STATUS_TABLE   = "/status-table",
  ACCEPT_STATUS_TABLE   = "/accept-status-table",
  GET_ORDER_TABLES      = "/order-table",
  ORDER_TABLE           = "/order-table",
  ORDER                 = "/order",
  ORDER_PAY_STATUS      = "/order/pay-status",
  ORDER_ITEM            = "/order-item",
  REPORT_MONTHLY        = "/order/monthly",
  // blog
  GET_LIST_BLOG    = "/blog",
  GET_BLOG         = "/blog",
  CREATE_BLOG      = "/blog",
  UPDATE_BLOG      = "/blog",
  DELETE_BLOG      = "/blog",
  SET_PUBLISH_BLOG = "/blog",
  // auth
  LOGIN_PASSWORD  = "/login-password",
  LOGIN_OTP       = "/login-otp",
  REFRESH_TOKEN   = "/refresh-token",
  UPDATE_PASSWORD = "/update-password",
  // user
  GET_ACCOUNT                      = "/account",
  UPDATE_ACCOUNT                   = "/account",
  GET_USER                         = "/user",
  CREATE_USER                      = "/user",
  UPDATE_USER                      = "/user",
  DELETE_USER                      = "/user",
  GET_DASHBOARD_CAPABILITY_USER    = "/dashboard-capability",
  CREATE_DASHBOARD_CAPABILITY_USER = "/dashboard-capability",
  DELETE_DASHBOARD_CAPABILITY_USER = "/dashboard-capability",
  GET_ROLE                         = "/role",
  CREATE_ROLE                      = "/role",
  UPDATE_ROLE                      = "/role",
  DELETE_ROLE                      = "/role",
  GET_ACCESS                       = "/access",
  // file
  GET_IMAGES           = "/image",
  UPLOAD_IMAGE_PRODUCT = "/image-product",
  UPLOAD_IMAGE         = "/image",
  DELETE_IMAGE         = "/image",
  // pricing
  GET_UNIT                           = "/unit",
  CREATE_UNIT                        = "/unit",
  DELETE_UNIT                        = "/unit",
  GET_PRODUCT_PRICING                = "/product",
  CREATE_PRODUCT_PRICING             = "/product",
  UPDATE_PRODUCT_PRICING             = "/product",
  DELETE_PRODUCT_PRICING             = "/product",
  CREATE_PRODUCT_PRICING_UNIT        = "/unit-product",
  UPDATE_PRODUCT_PRICING_UNIT        = "/unit-product",
  DELETE_PRODUCT_PRICING_UNIT        = "/unit-product",
  CREATE_DETAIL_PRODUCT_PRICING_UNIT = "/detail-product-unit",
  UPDATE_DETAIL_PRODUCT_PRICING_UNIT = "/detail-product-unit",
  DELETE_DETAIL_PRODUCT_PRICING_UNIT = "/detail-product-unit",
  CREATE_COST_PRODUCT_PRICING_UNIT   = "/cost",
  UPDATE_COST_PRODUCT_PRICING_UNIT   = "/cost",
  DELETE_COST_PRODUCT_PRICING_UNIT   = "/cost",
}
