export enum ERoute {
  HOST = "http://127.0.0.1:8080",
  // HOST = "http://192.168.1.100:8080",
  // HOST = "https://api.choconan.ir",
  // app
  GET_VIDEO      = "/get-video",
  GET_LAST_VIDEO = "/get-last-video",
  // menu
  GET_FULL_MENU                   = "/menu/get-menu",
  SEARCH_ON_MENU                  = "/menu/search",
  ADD_CATEGORY_MENU               = "/menu/category-menu",
  UPDATE_CATEGORY_MENU            = "/menu/category-menu",
  DELETE_CATEGORY_MENU            = "/menu/category-menu",
  ADD_PRODUCT_MENU                = "/menu/product-menu",
  UPDATE_PRODUCT_MENU             = "/menu/product-menu",
  DELETE_PRODUCT_MENU             = "/menu/product-menu",
  GET_ECONOMIC_PACKAGES           = "/menu/economic-package",
  ADD_ECONOMIC_PACKAGE            = "/menu/economic-package",
  UPDATE_ECONOMIC_PACKAGE         = "/menu/economic-package",
  DELETE_ECONOMIC_PACKAGE         = "/menu/economic-package",
  ADD_CONTENT_ECONOMIC_PACKAGE    = "/menu/content-economic-package",
  DELETE_CONTENT_ECONOMIC_PACKAGE = "/menu/content-economic-package",
  //service
  GET_CRAWLER_MENU_SNAP_FOOD      = "/service/crawler/menu-snap",
  GET_CRAWLER_MENU_TAPSI_FOOD     = "/service/crawler/menu-tapsi",
  // order
  GET_TABLES            = "/order/table",
  CREATE_TABLE          = "/order/table",
  DELETE_TABLE          = "/order/table",
  GET_STATUS_TABLE      = "/order/status-table",
  EDITABLE_STATUS_TABLE = "/order/status-table",
  DELETE_STATUS_TABLE   = "/order/status-table",
  ACCEPT_STATUS_TABLE   = "/order/accept-status-table",
  GET_ORDER_TABLES      = "/order/order-table",
  ORDER_TABLE           = "/order/order-table",
  ORDER                 = "/order/order",
  ORDER_ITEM            = "/order/order-item",
  // blog
  GET_LIST_BLOG    = "/blog/get-list-blog",
  GET_BLOG         = "/blog/get-blog",
  CREATE_BLOG      = "/blog/create-blog",
  UPDATE_BLOG      = "/blog/update-blog",
  DELETE_BLOG      = "/blog/delete-blog",
  SET_PUBLISH_BLOG = "/blog/set-publish-blog",
  // auth
  LOGIN_PASSWORD  = "/auth/login-password",
  LOGIN_OTP       = "/auth/login-otp",
  REFRESH_TOKEN   = "/auth/refresh-token",
  UPDATE_PASSWORD = "/auth/update-password",
  // user
  GET_ACCOUNT                      = "/user/account",
  UPDATE_ACCOUNT                   = "/user/account",
  GET_USER                         = "/user/user",
  CREATE_USER                      = "/user/user",
  UPDATE_USER                      = "/user/user",
  DELETE_USER                      = "/user/user",
  GET_DASHBOARD_CAPABILITY_USER    = "/user/dashboard-capability",
  ADD_DASHBOARD_CAPABILITY_USER    = "/user/dashboard-capability",
  REMOVE_DASHBOARD_CAPABILITY_USER = "/user/dashboard-capability",
  GET_ROLE                         = "/user/role",
  CREATE_ROLE                      = "/user/role",
  UPDATE_ROLE                      = "/user/role",
  DELETE_ROLE                      = "/user/role",
  GET_ACCESS                       = "/user/access",
  // file
  GET_IMAGES           = "/file/image",
  UPLOAD_IMAGE_PRODUCT = "/file/image-product",
  UPLOAD_IMAGE         = "/file/image",
  DELETE_IMAGE         = "/file/image",
}
